import { Activity, ArrowUpRight, BadgeIndianRupee, CircleDollarSign, CreditCard, UsersRound } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { AppShell } from '../components/layout/AppShell'
import { Badge, Card } from '../components/ui/Primitives'
import { spendingData } from '../data/demoData'
import { formatCurrency } from '../lib/utils'

const adminMetrics = [{ icon: UsersRound, label: 'Total users', value: '14,862', change: '+9.6%', tone: 'aqua' }, { icon: CreditCard, label: 'Transactions', value: '82,491', change: '+12.4%', tone: 'blue' }, { icon: CircleDollarSign, label: 'Total deposits', value: '₹5.8Cr', change: '+7.8%', tone: 'sand' }, { icon: Activity, label: 'Active now', value: '2,164', change: '+4.1%', tone: 'violet' }]
const users = [{ name: 'Priya Sharma', email: 'priya@horizon.in', status: 'Active', joined: 'Today', value: '₹84,250' }, { name: 'Rohan Kapoor', email: 'rohan.k@example.com', status: 'Active', joined: 'Today', value: '₹26,110' }, { name: 'Naina Iyer', email: 'naina@arc.in', status: 'Review', joined: 'Yesterday', value: '₹0' }, { name: 'Kabir Singh', email: 'kabir@northstar.io', status: 'Active', joined: 'Yesterday', value: '₹1,24,600' }]
export default function AdminPage() { return <AppShell title="Admin workspace" subtitle="MoneyFlow system overview"><div className="admin-alert"><span>◉</span><strong>All systems operational</strong><p>Platform health is looking good across all services.</p><a href="#status">View status</a></div><div className="admin-metric-grid">{adminMetrics.map(({ icon: Icon, ...metric }) => <Card key={metric.label} className={`admin-metric admin-${metric.tone}`}><span><Icon size={19} /></span><p>{metric.label}</p><strong>{metric.value}</strong><small><ArrowUpRight size={14} /> {metric.change} <i>this month</i></small></Card>)}</div><div className="content-grid admin-charts"><Card className="chart-card"><div className="card-title-row"><div><span className="eyebrow">PLATFORM GROWTH</span><h2>New users</h2></div><Badge tone="success">+ 18.2%</Badge></div><ResponsiveContainer width="100%" height={220}><AreaChart data={spendingData}><defs><linearGradient id="adminFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4bbabd" stopOpacity={0.25} /><stop offset="100%" stopColor="#4bbabd" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} /><Tooltip /><Area dataKey="income" stroke="#268d91" strokeWidth={2.5} fill="url(#adminFill)" /></AreaChart></ResponsiveContainer></Card><Card className="chart-card"><div className="card-title-row"><div><span className="eyebrow">PROCESSING VOLUME</span><h2>Transaction volume</h2></div><Badge tone="purple">Live</Badge></div><ResponsiveContainer width="100%" height={220}><BarChart data={spendingData}><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} /><Tooltip formatter={(value) => formatCurrency(value)} /><Bar dataKey="spending" fill="#7773ce" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></Card></div><Card className="admin-table"><div className="card-title-row"><div><span className="eyebrow">RECENT USERS</span><h2>Account activity</h2></div><a href="#users">View all users →</a></div><div className="admin-user-table"><div className="admin-user-head"><span>User</span><span>Status</span><span>Joined</span><span>Balance</span></div>{users.map((user) => <div key={user.email}><span className="user-line"><i>{user.name.charAt(0)}</i><b>{user.name}<small>{user.email}</small></b></span><Badge tone={user.status === 'Active' ? 'success' : 'warning'}>{user.status}</Badge><span>{user.joined}</span><strong>{user.value}</strong></div>)}</div></Card></AppShell> }
