import { useState } from 'react'
import * as Icons from 'lucide-react'
import { CalendarDays, CheckCircle2, Clock3, MoreHorizontal } from 'lucide-react'
import { AppShell, PageAction } from '../components/layout/AppShell'
import { Badge, Button, Card, Field, IconButton, Input, Modal, Select, Toast } from '../components/ui/Primitives'
import { bills as seedBills } from '../data/demoData'
import { formatCurrency } from '../lib/utils'

const billIcons = { wifi: Icons.Wifi, home: Icons.House, music: Icons.Music2, zap: Icons.Zap }
export default function BillsPage() {
  const [items, setItems] = useState(seedBills)
  const [open, setOpen] = useState(false)
  const [toast, setToast] = useState(null)
  const dueTotal = items.filter((item) => !item.paid).reduce((total, item) => total + item.amount, 0)
  const addBill = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setItems([...items, { id: crypto.randomUUID(), name: data.get('name'), category: data.get('category'), amount: Number(data.get('amount')), due: data.get('due') || '01 Sep', icon: 'zap', color: 'aqua', paid: false }]); setOpen(false); setToast({ message: 'Bill scheduled for tracking.', type: 'success' }) }
  const pay = (id) => { setItems(items.map((item) => item.id === id ? { ...item, paid: true } : item)); setToast({ message: 'Bill marked as paid — nicely done.', type: 'success' }) }
  return <AppShell title="Bills & payments" subtitle="Keep the essentials on track" action={<PageAction onClick={() => setOpen(true)}>Add bill</PageAction>}><div className="bills-summary"><Card><span className="eyebrow">UPCOMING THIS MONTH</span><strong>{formatCurrency(dueTotal)}</strong><p>Across {items.filter((item) => !item.paid).length} bills</p></Card><Card className="bills-date-card"><CalendarDays size={20} /><div><strong>Next payment due</strong><p>Airtel Broadband · tomorrow</p></div><Button size="sm" onClick={() => pay(1)}>Pay now</Button></Card></div><div className="bills-layout"><Card className="bills-list"><div className="card-title-row"><div><span className="eyebrow">COMING UP</span><h2>Upcoming bills</h2></div><Button variant="ghost" size="sm">View calendar</Button></div>{items.filter((item) => !item.paid).map((item) => <BillRow item={item} pay={pay} key={item.id} />)}</Card><Card className="autopay-card"><span className="auto-illustration"><Clock3 size={29} /></span><span className="eyebrow">NEVER MISS A DUE DATE</span><h2>Make payments effortless</h2><p>Set reminders for your bills and keep one less thing on your mind.</p><Button variant="secondary">Manage reminders</Button></Card></div><Card className="paid-bills"><div className="card-title-row"><div><span className="eyebrow">PAST PAYMENTS</span><h2>Paid bills</h2></div><Badge tone="success">{items.filter((item) => item.paid).length} paid</Badge></div>{items.filter((item) => item.paid).map((item) => <BillRow item={item} pay={pay} key={item.id} />)}</Card><Modal open={open} onClose={() => setOpen(false)} title="Add a bill"><form className="stack-form" onSubmit={addBill}><Field label="Bill name"><Input name="name" required placeholder="e.g. Gym membership" /></Field><div className="form-two"><Field label="Category"><Select name="category"><option>Electricity</option><option>Internet</option><option>Mobile</option><option>Rent</option><option>Subscription</option><option>Insurance</option></Select></Field><Field label="Amount"><Input name="amount" type="number" min="1" required placeholder="0" /></Field></div><Field label="Due date"><Input name="due" placeholder="e.g. 18 Aug" /></Field><div className="modal-actions"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit">Add bill</Button></div></form></Modal><Toast {...(toast || {})} onClose={() => setToast(null)} /></AppShell>
}
function BillRow({ item, pay }) { const Icon = billIcons[item.icon] || Icons.Receipt; return <div className="bill-row"><span className={`bill-icon bill-${item.color}`}><Icon size={19} /></span><div><strong>{item.name}</strong><small>{item.category}</small></div><span className="bill-due"><CalendarDays size={14} /> {item.paid ? 'Paid' : `Due ${item.due}`}</span><b>{formatCurrency(item.amount)}</b>{item.paid ? <Badge tone="success"><CheckCircle2 size={13} /> Paid</Badge> : <Button size="sm" variant="secondary" onClick={() => pay(item.id)}>Pay now</Button>}<IconButton label={`Options for ${item.name}`}><MoreHorizontal size={17} /></IconButton></div> }
