import { useState } from 'react'
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowRight, ChevronRight, CircleDollarSign, MoreHorizontal, Plus, Send, WalletCards } from 'lucide-react'
import { motion } from 'framer-motion'
import { AppShell, PageAction } from '../components/layout/AppShell'
import { MetricCard } from '../components/dashboard/MetricCard'
import { TransactionTable } from '../components/dashboard/TransactionTable'
import { Button, Card, IconButton, Modal } from '../components/ui/Primitives'
import { accounts, categoryData, spendingData, transactions } from '../data/demoData'
import { formatCurrency } from '../lib/utils'
import { useAuth } from '../context/AuthContext'

const chartTooltip = { cursor: { fill: 'transparent' }, contentStyle: { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, boxShadow: '0 10px 20px rgba(10,31,38,.08)' }, labelStyle: { color: 'var(--muted)' }, itemStyle: { color: 'var(--text)' }, formatter: (value) => formatCurrency(value) }

function BalanceCard() { return <Card className="balance-card"><div className="balance-card-top"><span>Total balance</span><IconButton label="Account options"><MoreHorizontal size={19} /></IconButton></div><strong>{formatCurrency(84250)}</strong><div className="balance-card-bottom"><span className="balance-growth">↑ 8.2% <i>vs last month</i></span><span>•••• 4928</span></div><div className="balance-card-lines"><i /><i /><i /></div></Card> }
function QuickAction({ icon: Icon, label, text, onClick }) { return <button className="quick-action" onClick={onClick}><span><Icon size={19} /></span><div><strong>{label}</strong><small>{text}</small></div><ChevronRight size={18} /></button> }

export default function DashboardPage() {
  const { user } = useAuth()
  const [transferOpen, setTransferOpen] = useState(false)
  const [transaction, setTransaction] = useState(null)
  const firstName = (user?.displayName || user?.email || 'there').trim().split(/\s|@/)[0]
  return <AppShell title={`Good morning, ${firstName}`} subtitle="Your financial overview" action={<PageAction onClick={() => setTransferOpen(true)}>Send money</PageAction>}>
    <motion.div className="dashboard-hero" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><div className="dashboard-hero-copy"><span className="eyebrow">YOUR FINANCIAL OVERVIEW</span><h2>Every rupee has a place.<br /><em>See yours clearly.</em></h2><p>Here’s a gentle snapshot of your finances this month.</p></div><BalanceCard /></motion.div>
    <div className="metric-grid"><MetricCard label="Available to spend" value={77500} change={12.4} hint="after bills & goals" /><MetricCard label="Monthly income" value={52000} change={8.2} tone="blue" /><MetricCard label="Monthly spending" value={31750} change={4.8} tone="sand" hint="61% of your income" /><MetricCard label="Savings this month" value={20250} change={18.6} tone="violet" /></div>
    <div className="content-grid main-charts"><Card className="chart-card spending-chart"><div className="card-title-row"><div><span className="eyebrow">SPENDING ANALYTICS</span><h2>Cash flow</h2></div><select className="period-select" defaultValue="6 months"><option>6 months</option><option>This year</option></select></div><div className="chart-legend"><span><i className="legend-income" />Income</span><span><i className="legend-spending" />Spending</span></div><ResponsiveContainer width="100%" height={245}><AreaChart data={spendingData} margin={{ top: 12, right: 4, left: -22, bottom: 0 }}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4bbabd" stopOpacity={0.22} /><stop offset="100%" stopColor="#4bbabd" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} dy={9} /><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} tickFormatter={(value) => `₹${value / 1000}k`} /><Tooltip {...chartTooltip} /><Area type="monotone" dataKey="income" stroke="#268d91" strokeWidth={2.4} fill="url(#incomeFill)" /><Area type="monotone" dataKey="spending" stroke="#e1a14f" strokeWidth={2.4} fill="transparent" /></AreaChart></ResponsiveContainer></Card>
      <Card className="chart-card category-card"><div className="card-title-row"><div><span className="eyebrow">AUGUST 2026</span><h2>Where it went</h2></div><IconButton label="More spending details"><MoreHorizontal size={19} /></IconButton></div><div className="pie-wrap"><ResponsiveContainer width="100%" height={185}><PieChart><Pie data={categoryData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={76} paddingAngle={3} stroke="none">{categoryData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip {...chartTooltip} /></PieChart></ResponsiveContainer><div className="pie-center"><strong>₹31.8k</strong><span>spent</span></div></div><div className="category-list">{categoryData.slice(0, 4).map((item) => <span key={item.name}><i style={{ backgroundColor: item.color }} />{item.name}<b>{formatCurrency(item.value)}</b></span>)}</div></Card>
    </div>
    <div className="content-grid lower-grid"><Card className="transactions-card"><div className="card-title-row"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Transactions</h2></div><Button variant="ghost" size="sm" onClick={() => window.location.assign('/transactions')}>View all <ArrowRight size={15} /></Button></div><TransactionTable items={transactions.slice(0, 5)} compact onSelect={setTransaction} /></Card>
      <Card className="actions-card"><div><span className="eyebrow">MOVE MONEY</span><h2>Quick actions</h2></div><div className="quick-action-list"><QuickAction icon={Send} label="Send money" text="To a person or account" onClick={() => setTransferOpen(true)} /><QuickAction icon={Plus} label="Add money" text="Top up your balance" onClick={() => setTransferOpen(true)} /><QuickAction icon={CircleDollarSign} label="Pay a bill" text="Keep things moving" onClick={() => window.location.assign('/bills')} /><QuickAction icon={WalletCards} label="View accounts" text="Your financial home" onClick={() => window.location.assign('/accounts')} /></div></Card>
    </div>
    <Modal open={transferOpen} onClose={() => setTransferOpen(false)} title="Start a transfer"><div className="modal-copy"><div className="modal-icon"><Send size={22} /></div><h3>Where should it go?</h3><p>Use the secure transfer form to move money between accounts or to someone you know.</p></div><div className="modal-actions"><Button variant="secondary" onClick={() => setTransferOpen(false)}>Cancel</Button><Button onClick={() => window.location.assign('/transfers')}>Continue <ArrowRight size={16} /></Button></div></Modal>
    <Modal open={Boolean(transaction)} onClose={() => setTransaction(null)} title="Transaction details">{transaction && <div className="transaction-detail"><div className="detail-amount"><span>{transaction.amount >= 0 ? 'Money in' : 'Money out'}</span><strong className={transaction.amount >= 0 ? 'income' : ''}>{transaction.amount >= 0 ? '+' : '−'}{formatCurrency(Math.abs(transaction.amount))}</strong></div><dl><div><dt>Merchant</dt><dd>{transaction.merchant}</dd></div><div><dt>Category</dt><dd>{transaction.category}</dd></div><div><dt>Date</dt><dd>{transaction.date}</dd></div><div><dt>Status</dt><dd>{transaction.status}</dd></div></dl></div>}</Modal>
  </AppShell>
}
