import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ArrowDownUp, Download, Filter, Search } from 'lucide-react'
import { AppShell, PageAction } from '../components/layout/AppShell'
import { Badge, Button, Card, Field, Input, Modal, Select, Toast } from '../components/ui/Primitives'
import { TransactionTable } from '../components/dashboard/TransactionTable'
import { transactions as seededTransactions } from '../data/demoData'
import { formatCurrency } from '../lib/utils'
import { useUserCollection } from '../firebase/data'

export default function TransactionsPage() {
  const [searchParams] = useSearchParams()
  const { items, saveItem, removeItem } = useUserCollection('transactions', seededTransactions)
  const [query, setQuery] = useState(() => searchParams.get('search') || '')
  const [category, setCategory] = useState('All categories')
  const [status, setStatus] = useState('All statuses')
  const [sort, setSort] = useState('newest')
  const [selected, setSelected] = useState(null)
  const [addOpen, setAddOpen] = useState(false)
  const [toast, setToast] = useState(null)
  useEffect(() => setQuery(searchParams.get('search') || ''), [searchParams])
  const filtered = useMemo(() => [...items].filter((item) => `${item.title} ${item.merchant}`.toLowerCase().includes(query.toLowerCase())).filter((item) => category === 'All categories' || item.category === category).filter((item) => status === 'All statuses' || item.status === status).sort((a, b) => sort === 'newest' ? new Date(b.date) - new Date(a.date) : Math.abs(b.amount) - Math.abs(a.amount)), [category, items, query, sort, status])
  const summary = { income: items.filter((item) => item.amount > 0).reduce((total, item) => total + item.amount, 0), outgoing: Math.abs(items.filter((item) => item.amount < 0).reduce((total, item) => total + item.amount, 0) ) }
  const save = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const amount = Number(data.get('amount')); const entry = { id: crypto.randomUUID(), title: data.get('title'), merchant: data.get('merchant') || 'Manual entry', category: data.get('category'), date: data.get('date'), amount: data.get('kind') === 'income' ? amount : -amount, status: 'Completed', type: data.get('kind'), icon: data.get('kind') === 'income' ? 'briefcase' : 'shopping-basket' }; try { await saveItem(entry); setAddOpen(false); setToast({ message: 'Transaction added.', type: 'success' }) } catch (error) { setToast({ message: error.message, type: 'error' }) } }
  const exportTransactions = () => { const rows = filtered.map((item) => [item.date, item.title, item.merchant, item.category, item.amount, item.status].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')); const url = URL.createObjectURL(new Blob([['Date,Title,Merchant,Category,Amount,Status', ...rows].join('\n')], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'moneyflow-transactions.csv'; link.click(); URL.revokeObjectURL(url) }
  const removeSelected = async () => { try { await removeItem(selected.id); setSelected(null); setToast({ message: 'Transaction deleted.', type: 'success' }) } catch (error) { setToast({ message: error.message, type: 'error' }) } }
  return <AppShell title="Transactions" subtitle="Everything that moved through your accounts" action={<PageAction onClick={() => setAddOpen(true)}>Add transaction</PageAction>}>
    <div className="transaction-summary"><Card><span>Money in</span><strong className="income">{formatCurrency(summary.income)}</strong><small>Current activity</small></Card><Card><span>Money out</span><strong>{formatCurrency(summary.outgoing)}</strong><small>Current activity</small></Card><Card><span>Net flow</span><strong className="income">{formatCurrency(summary.income - summary.outgoing)}</strong><small>Based on listed transactions</small></Card></div>
    <Card className="filters-card"><div className="filters-head"><div><span className="eyebrow">ALL ACTIVITY</span><h2>{filtered.length} transactions</h2></div><Button variant="secondary" size="sm" onClick={exportTransactions}><Download size={15} /> Export</Button></div><div className="filters"><div className="filter-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search transactions" /></div><Select value={category} onChange={(event) => setCategory(event.target.value)}><option>All categories</option><option>Income</option><option>Food & dining</option><option>Bills & utilities</option><option>Travel</option><option>Investments</option></Select><Select value={status} onChange={(event) => setStatus(event.target.value)}><option>All statuses</option><option>Completed</option><option>Pending</option><option>Failed</option></Select><Button variant="ghost" size="sm"><Filter size={15} /> More filters</Button></div><div className="table-sort"><span>Showing your latest activity</span><label><ArrowDownUp size={14} /> Sort <Select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="amount">Highest amount</option></Select></label></div><TransactionTable items={filtered} onSelect={setSelected} /><div className="pagination"><span>Showing {filtered.length} of {items.length} transactions</span></div></Card>
    <Modal open={Boolean(selected)} onClose={() => setSelected(null)} title="Transaction details">{selected && <TransactionDetails item={selected} onDelete={removeSelected} />}</Modal><Modal open={addOpen} onClose={() => setAddOpen(false)} title="Add a transaction"><form className="stack-form" onSubmit={save}><Field label="Transaction name"><Input name="title" required placeholder="e.g. Coffee with team" /></Field><div className="form-two"><Field label="Amount"><Input name="amount" type="number" min="1" required placeholder="0" /></Field><Field label="Type"><Select name="kind"><option value="expense">Expense</option><option value="income">Income</option></Select></Field></div><Field label="Category"><Select name="category"><option>Food & dining</option><option>Shopping</option><option>Bills & utilities</option><option>Travel</option><option>Income</option><option>Other</option></Select></Field><Field label="Date"><Input name="date" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></Field><div className="modal-actions"><Button variant="secondary" type="button" onClick={() => setAddOpen(false)}>Cancel</Button><Button type="submit">Save transaction</Button></div></form></Modal><Toast {...(toast || {})} onClose={() => setToast(null)} />
  </AppShell>
}

function TransactionDetails({ item, onDelete }) { return <div className="transaction-detail"><div className="detail-amount"><span>{item.amount > 0 ? 'Money in' : 'Money out'}</span><strong className={item.amount > 0 ? 'income' : ''}>{item.amount > 0 ? '+' : '−'}{formatCurrency(Math.abs(item.amount))}</strong></div><dl><div><dt>Recipient / merchant</dt><dd>{item.merchant}</dd></div><div><dt>Category</dt><dd>{item.category}</dd></div><div><dt>When</dt><dd>{item.date}</dd></div><div><dt>State</dt><dd><Badge tone={item.status === 'Pending' ? 'warning' : 'success'}>{item.status}</Badge></dd></div></dl><div className="modal-actions"><Button variant="danger" onClick={onDelete}>Delete transaction</Button><Button onClick={() => window.print()}>Download receipt</Button></div></div> }
